export const tutors = [
    {
        slug: "amanSharma",
        name: "Aman Sharma",
        subject: "Physics Expert",
        title: "Senior Physics Faculty | JEE, NEET & Board Exam Expert",
        rating: "4.9",
        students: "12K+",
        initials: "AS",
        img: "/teachers/teacher1.png",
        description: "A passionate Physics educator dedicated to making complex concepts simple and engaging. With extensive teaching experience in Class 9-12 Physics, JEE, and NEET preparation, I focus on conceptual clarity, problem-solving skills, and exam-oriented strategies. My goal is to help every student build confidence and achieve outstanding academic results.",
        specializations: [
            "Class 9-12 Physics",
            "JEE Main & Advanced Preparation",
            "NEET Physics Preparation",
            "CBSE, ICSE & State Boards",
            "Concept-Based Learning",
            "Doubt Solving & Test Preparation"
        ],
        experience: "5+ Years",
        language: "Hindi & English",
        quote: "Success in Physics comes from understanding concepts, not memorizing formulas."
    },
    {
        slug: "nehaAgarwal",
        name: "Neha Agarwal",
        subject: "Maths Expert",
        title: "Senior Mathematics Faculty | CBSE, ICSE & Competitive Exam Expert",
        rating: "4.8",
        students: "960+",
        initials: "NA",
        img: "/teachers/teacher2.png",
        description: "A dedicated Mathematics educator with a passion for helping students develop strong analytical and problem-solving skills. Specializing in school-level Mathematics and competitive exam preparation, I focus on simplifying complex concepts and building confidence through structured learning and regular practice.",
        specializations: [
            "Class 6-12 Mathematics",
            "CBSE, ICSE & State Boards",
            "Foundation Courses for JEE & Olympiads",
            "Algebra, Geometry & Calculus",
            "Exam Preparation & Doubt Solving",
            "Concept-Based Learning Approach"
        ],
        experience: "4+ Years",
        language: "Hindi & English",
        quote: "Mathematics is not about memorizing formulas—it's about understanding patterns and solving problems with confidence."
    },
    {
        slug: "rohitVerma",
        name: "Rohit Verma",
        subject: "Chemistry Expert",
        title: "Senior Chemistry Faculty | NEET, JEE & Board Exam Expert",
        rating: "4.9",
        students: "11K+",
        initials: "RV",
        img: "/teachers/teacher3.png",
        description: "An experienced Chemistry educator dedicated to helping students master Physical, Organic, and Inorganic Chemistry through concept-based learning. With a student-focused teaching approach, I simplify complex topics, strengthen problem-solving abilities, and prepare students for academic excellence and competitive examinations.",
        specializations: [
            "Class 9-12 Chemistry",
            "NEET Chemistry Preparation",
            "JEE Main & Advanced Chemistry",
            "CBSE, ICSE & State Boards",
            "Organic, Inorganic & Physical Chemistry",
            "Doubt Solving & Exam-Oriented Practice"
        ],
        experience: "6+ Years",
        language: "Hindi & English",
        quote: "Chemistry becomes easy when concepts are understood, not memorized."
    },
    {
        slug: "priyaSingh",
        name: "Priya Singh",
        subject: "English Expert",
        title: "Senior English Faculty | Spoken English, Grammar & Communication Expert",
        rating: "4.8",
        students: "820+",
        initials: "PS",
        img: "/teachers/teacher4.png",
        description: "A dedicated English educator passionate about helping students improve their language skills, communication abilities, and academic performance. With a student-friendly teaching approach, I focus on grammar, vocabulary, spoken English, writing skills, and confidence building to help learners excel in both academics and everyday communication.",
        specializations: [
            "Spoken English & Communication Skills",
            "English Grammar & Vocabulary",
            "Class 6-12 English",
            "CBSE, ICSE & State Boards",
            "Reading, Writing & Comprehension Skills",
            "Interview & Personality Development"
        ],
        experience: "4+ Years",
        language: "English & Hindi",
        quote: "Learning English is not just about language—it's about building confidence and unlocking new opportunities."
    },
    {
        slug: "rituGarg",
        name: "Ritu Garg",
        subject: "Accountancy Expert",
        title: "Senior Accountancy Faculty | Accountancy, Finance & Commerce Expert",
        rating: "4.8",
        students: "820+",
        initials: "RG",
        img: "/teachers/teacher5.png",
        description: "A dedicated Accountancy educator passionate about helping students understand accounting concepts with clarity and confidence. With a practical and student-friendly teaching approach, I focus on strengthening fundamentals, improving problem-solving skills, and preparing learners for academic excellence.",
        specializations: [
            "Accountancy & Financial Accounting",
            "Journal, Ledger & Trial Balance",
            "Final Accounts & Partnership Accounts",
            "Class 11-12 Accountancy",
            "CBSE, ICSE & State Boards",
            "Financial Statements & Accounting Concepts",
            "Exam Preparation & Problem Solving",
            "Commerce & Business Studies Support"
        ],
        experience: "4+ Years",
        language: "English & Hindi",
        quote: "Accountancy is not just about numbers—it's about understanding the logic behind every transaction and building a strong foundation for success."
    },
    {
        slug: "ashutosh",
        name: "Ashutosh",
        subject: "Hindi Expert",
        title: "Senior Hindi Faculty | Hindi Language, Grammar & Literature Expert",
        rating: "4.8",
        students: "820+",
        initials: "A",
        img: "/teachers/teacher6.png",
        description: "A dedicated Hindi educator passionate about helping students develop strong language skills, improve their grammar, and build a deeper understanding of Hindi literature. With a student-friendly and engaging teaching approach, I focus on conceptual clarity, writing skills, vocabulary, comprehension, and exam preparation.",
        specializations: [
            "Hindi Grammar & Vocabulary",
            "Hindi Literature & Language",
            "Class 6-12 Hindi",
            "CBSE, ICSE & State Boards",
            "Reading, Writing & Comprehension",
            "Essay, Letter & Creative Writing",
            "Board Exam Preparation",
            "Hindi Language & Communication Skills"
        ],
        experience: "4+ Years",
        language: "Hindi & English",
        quote: "Hindi is not just a language—it's a beautiful expression of knowledge, culture, and confidence."
    },
    {
        slug: "poornimaMittal",
        name: "Poornima Mittal",
        subject: "Biology Expert",
        title: "Senior Biology Faculty | Biology, Life Sciences & NEET Expert",
        rating: "4.8",
        students: "820+",
        initials: "PM",
        img: "/teachers/teacher7.png",
        description: "A dedicated Biology educator passionate about making complex biological concepts simple, engaging, and easy to understand. With a student-friendly teaching approach, I focus on conceptual clarity, diagrams, problem-solving, and exam-oriented preparation to help students achieve academic excellence.",
        specializations: [
            "Biology & Life Sciences",
            "Class 9-12 Biology",
            "CBSE, ICSE & State Boards",
            "Human Physiology & Genetics",
            "Botany & Zoology",
            "Cell Biology & Molecular Biology",
            "NEET Biology Preparation",
            "NCERT-Based Exam Preparation"
        ],
        experience: "4+ Years",
        language: "English & Hindi",
        quote: "Biology is the study of life—and understanding life begins with understanding its concepts."
    },
    {
        slug: "anubKasana",
        name: "Anub Kasana",
        subject: "Spoken English Expert",
        title: "Senior Spoken English Faculty | Communication & Personality Development Expert",
        rating: "4.8",
        students: "820+",
        initials: "AK",
        img: "/teachers/teacher8.png",
        description: "A dedicated Spoken English educator passionate about helping learners communicate confidently and effectively in English. With a practical and interactive teaching approach, I focus on improving fluency, pronunciation, vocabulary, grammar, and overall communication skills to help students succeed in academic, professional, and everyday conversations.",
        specializations: [
            "Spoken English & Fluency",
            "English Grammar & Vocabulary",
            "Communication Skills",
            "Pronunciation & Accent Improvement",
            "Public Speaking & Presentation Skills",
            "Interview & Personality Development",
            "Conversational English",
            "Confidence Building"
        ],
        experience: "3+ Years",
        language: "English & Hindi",
        quote: "Fluent English is not just about speaking correctly—it's about speaking with confidence."
    }
];
